services:
  wikmd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wikmd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./wiki:/wiki
    ports:
      - "5000:5000"
    restart: unless-stopped
